### ISSUE TITLE
Improve StatefulView

### ISSUE THREAD

**Issue by brendanlensink** [steamclock/nice_components#24]
- The order that you pass in params is weird, IMO it should be load state, then all the views
- It would be nice if you can pass in `some View` rather than `AnyView`
- The loading indicator doesn't size properly all the time, it should have some vertical padding by default

**Comment by AZielinsky95** [comment]
I don't even think this view should be part of NiceComponents personally as it works on ContentLoadState which is more appropriate to add to an architecture library like our MVVM library. If an app implements this framework we shouldn't be dictating anything about how it should be handling view state and instead should just be providing a component library that is completely agnostic of app architecture other than it being a SwiftUI app obviously.

**Comment by AZielinsky95** [comment]
@brendanlensink @nbrooke Wondering what you guys think. I want to work on our next update for this library and want to resolve this. Are we ok with deleting StatefulView/ContentLoadState or any strong opinions on why it should be included? 

We can just re-implement the opaque view version in Ridwell along with the load state enum

**Comment by nbrooke** [comment]
Sorry for the slow reply, had this in my inbox meaning to respond but never got around to it. 

ContentLoadState and a view that uses it to switch states is definitely one of those things that we end up needing something similar in a lot of apps, so it would be nice to have a well defined way to do it. It might make more sense as part of an MVVM / architecture sort of library but a) we don't really have one of those right now, just some vague guidelines, and b) I feel like to be as easy to use as possible, it needs to be plumbed down to the view level anyway. 

I'm not opposed to removing it if there are problems with using it that we don't think are correctable (looking at the current use, it does seem like we have re-implimented it in the main app of ours that is using the library so it may be that there are some things that make it too hard to use to justify.
